#!/usr/bin/env python3
"""Generate identical standalone trust guards for the legacy delivery seam."""
import pathlib
import json

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = ROOT / "hermes_converger/step0"
contain = (BASE / "contain.sh").read_text()
start = contain.index("/usr/bin/awk '") + len("/usr/bin/awk '")
end = contain.index("' \"$f\"", start)
contain = contain[:start] + (BASE / "sudoers.awk").read_text() + contain[end:]
(BASE / "contain.sh").write_text(contain)
TRUST = (BASE / "trust.sh").read_text().split("\n", 1)[1] + (BASE / "contain.sh").read_text().split("\n", 1)[1]
# env -i is before any external helper or imported file. Noninteractive /bin/sh
# reads no ENV/BASH_ENV; sudo also strips dynamic loader variables before exec.
PREFIX = '''#!/bin/sh
# Generated by scripts/render-currency-step0.py; takes NO caller arguments.
[ "$#" = 0 ] || { echo 'chief: arguments refused' >&2; exit 2; }
exec /usr/bin/env -i PATH=/usr/bin:/bin:/usr/sbin:/sbin HOME=/var/empty LANG=C /bin/sh -s <<'CHIEF_TRUSTED_BODY'
cd /
umask 027
'''
for name, mode in (("hermes-converger", "converge"), ("chief-node-supervisor", "supervisor"), ("chief-update", "update")):
    body = PREFIX + TRUST + '''
[ "$(/usr/bin/id -u)" = 0 ] || { hold 'root service entry point'; exit 1; }
BASE=/usr/local/lib/hermes-host-bootstrap/hermes_converger/step0
trusted_path /usr/local/bin/''' + name + ''' || contain unsafe_launcher_path
trusted_path "$BASE/trust.sh" || contain unsafe_payload_path
'''
    if mode == "converge":
        body += '''if [ ! -f /var/lib/chief/currency-step0/prepared ]; then
    trusted_tree /usr/local/lib/hermes-host-bootstrap/hermes_converger || contain unsafe_payload_tree
    exec /bin/sh "$BASE/close.sh"
fi
trusted_path /var/lib/chief/currency-step0/prepared || contain unsafe_state
trusted_path "$BASE/pulse.sh" || contain unsafe_pulse
exec /bin/sh "$BASE/pulse.sh"
'''
    elif mode == "supervisor":
        body += '''trusted_tree /usr/local/lib/hermes-host-bootstrap/hermes_converger || contain unsafe_payload_tree
trusted_python || contain trusted_python_unavailable
exec "$PY" -I -S -B -c 'import sys; sys.path.insert(0,"/usr/local/lib/hermes-host-bootstrap"); from hermes_converger.runtime import run; raise SystemExit(run("supervisor"))'
'''
    else:
        body += '''trusted_tree /usr/local/lib/hermes-host-bootstrap/hermes_converger || contain unsafe_payload_tree
exec /bin/sh "$BASE/update.sh"
'''
    body += "CHIEF_TRUSTED_BODY\n"
    (ROOT / "scripts" / name).write_text(body)
    (BASE / "bin").mkdir(exist_ok=True)
    (BASE / "bin" / name).write_text(body)

for folder, pattern in (("systemd", "chief-*"), ("launchd", "com.chief.*.plist")):
    for source in (ROOT / folder).glob(pattern):
        if not source.is_file() or source.name in {"chief-node.service", "chief-update-login.service", "com.chief.node.plist"}:
            continue
        (BASE / folder).mkdir(exist_ok=True)
        (BASE / folder / source.name).write_bytes(source.read_bytes())
for source, target in (("systemd/chief-update-login.service", "chief-update-login.service"),
                       ("scripts/chief-update-resume", "chief-update-resume"),
                       ("scripts/chief-update-request", "bin/chief-update-request")):
    (BASE / target).write_bytes((ROOT / source).read_bytes())

# Snapshot of the authoritative host registry, not a separate SSH inventory.
(BASE / "hosts").mkdir(exist_ok=True)
for node, record in json.loads((BASE / "host-contracts.json").read_text()).items():
    data = {"CHIEF_NODE_ID": node, "CHIEF_CORE_URL": record["CHIEF_CORE_URL"],
            "CHIEF_RUNTIME_USER": record["runtime_user"], "REGISTRY_FQDN": record["fqdn"]}
    (BASE / "hosts" / (node + ".env")).write_text("".join(f"{k}={v}\n" for k, v in data.items()))
