#!/usr/bin/env python3
"""Generate identical standalone trust guards for the legacy delivery seam."""
import pathlib
import json
import shlex
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = ROOT / "hermes_converger/step0"
registry = json.loads((BASE / "host-contracts.json").read_text())
users = sorted({v["runtime_user"] for v in registry.values()} - {"root"})
contain = (BASE / "contain.sh").read_text()
contain = re.sub(r"for user in .*; do # generated runtime users", "for user in " + " ".join(shlex.quote(u) for u in users) + "; do # generated runtime users", contain)
start = contain.index("/usr/bin/awk '") + len("/usr/bin/awk '")
end = contain.index("' \"$f\"", start)
contain = contain[:start] + (BASE / "sudoers.awk").read_text() + contain[end:]
(BASE / "contain.sh").write_text(contain)
TRUST = (BASE / "trust.sh").read_text().split("\n", 1)[1] + (BASE / "contain.sh").read_text().split("\n", 1)[1]
# Inside env -i these are Bash's own variables (macOS /bin/sh), never caller
# input. Other POSIX shells keep the portable uname/id fallback.
TRUST = TRUST.replace('TRUST_OS=$(/usr/bin/uname -s)', '''case ${OSTYPE:-} in
    darwin*) TRUST_OS=Darwin;;
    linux*) TRUST_OS=Linux;;
    *) TRUST_OS=$(/usr/bin/uname -s);;
esac''', 1)
# env -i is before any external helper or imported file. Noninteractive /bin/sh
# reads no ENV/BASH_ENV; sudo also strips dynamic loader variables before exec.
PREFIX = '''#!/bin/sh
# Generated by scripts/render-currency-step0.py; takes NO caller arguments.
[ "$#" = 0 ] || { echo 'chief: arguments refused' >&2; exit 2; }
'''
for name, mode in (("hermes-converger", "converge"), ("chief-node-supervisor", "supervisor"), ("chief-update", "update")):
    body = "cd /\numask 027\n" + TRUST + '''
[ "${EUID:-$(/usr/bin/id -u)}" = 0 ] || { hold 'root service entry point'; exit 1; }
BASE=/opt/chief/lib/hermes-host-bootstrap/hermes_converger/step0
if [ ! -d "$BASE" ]; then
    # One-time bridge from the legacy updater's fixed copy destinations. On an
    # untrusted /usr/local chain use the reviewed root archive route instead.
    trusted_path /usr/local/bin/''' + name + ''' || refuse unsafe_launcher_path
    trusted_tree /usr/local/lib/hermes-host-bootstrap/hermes_converger || refuse unsafe_payload_tree
    for dir in /opt /opt/chief /opt/chief/lib /opt/chief/lib/hermes-host-bootstrap /opt/chief/bin; do
        if [ ! -e "$dir" ]; then /usr/bin/install -d -o root -m 0755 "$dir"; fi
        trusted_path "$dir" || refuse unsafe_destination
    done
    bridge=$(/usr/bin/mktemp -d /opt/chief/lib/hermes-host-bootstrap/.bridge.XXXXXX)
    trap '/bin/rm -rf "$bridge"' EXIT
    /bin/cp -R /usr/local/lib/hermes-host-bootstrap/hermes_converger "$bridge/"
    trusted_tree "$bridge/hermes_converger" || refuse unsafe_bridge
    /bin/mv "$bridge/hermes_converger" /opt/chief/lib/hermes-host-bootstrap/hermes_converger
    /bin/rm -rf "$bridge"
    trap - EXIT
fi
# Only the installed fixed entries use the batched check. During initial closure
# use the full tree check; no root-owned state or config is assumed to exist yet.
STATE=/var/lib/chief/currency-step0
if [ -f "$STATE/prepared" ]; then
    trusted_entries || refuse unsafe_entry_chain
else
    trusted_path "$BASE/trust.sh" || refuse unsafe_payload_path
    trusted_tree "$BASE/.." || refuse unsafe_payload_tree
    exec /bin/sh "$BASE/close.sh"
fi
if [ ! -f "$STATE/grants-removed" ]; then
    read_state revocation-retry 0
    case "$value" in ''|*[!0-9]*) value=0;; esac
    now=$(/bin/date +%s)
    if [ "$now" -ge "$value" ] || [ "$value" -gt "$((now + 900))" ]; then
        trusted_tree "$BASE/.." || refuse unsafe_payload_tree
        exec /bin/sh "$BASE/close.sh"
    fi
    # Safe readers still check in and report health during a revocation hold.
fi
'''
    script = {"converge": "pulse", "supervisor": "supervise", "update": "update"}[mode]
    if mode == "update":
        body += 'trusted_tree "$BASE/.." || refuse unsafe_payload_tree\n'
        body += 'exec /bin/sh "$BASE/update.sh"\n'
    else:
        # Keep the already checked embedded helpers and OS identity in this shell.
        body += f'. "$BASE/{script}.sh"\n'
    rendered = PREFIX + "exec /usr/bin/env -i PATH=/usr/bin:/bin:/usr/sbin:/sbin HOME=/var/empty LANG=C /bin/sh -c " + shlex.quote(body) + "\n"
    (ROOT / "scripts" / name).write_text(rendered)
    (BASE / "bin").mkdir(exist_ok=True)
    (BASE / "bin" / name).write_text(rendered)

for folder, pattern in (("systemd", "chief-*"), ("launchd", "com.chief.*.plist")):
    for source in (ROOT / folder).glob(pattern):
        if not source.is_file() or source.name in {"chief-node.service", "chief-update-login.service", "com.chief.node.plist"}:
            continue
        (BASE / folder).mkdir(exist_ok=True)
        (BASE / folder / source.name).write_bytes(source.read_bytes())
for source, target in (("systemd/chief-update-login.service", "chief-update-login.service"),
                       ("scripts/chief-update-resume", "chief-update-resume"),
                       ("scripts/chief-update-request", "bin/chief-update-request")):
    (BASE / target).write_bytes((ROOT / source).read_bytes())

# Snapshot of the authoritative host registry, not a separate SSH inventory.
(BASE / "hosts").mkdir(exist_ok=True)
for old in (BASE / "hosts").glob("*.env"):
    if old.stem not in registry:
        old.unlink()
for node, record in registry.items():
    data = {"CHIEF_NODE_ID": node, "CHIEF_CORE_URL": record["CHIEF_CORE_URL"],
            "CHIEF_RUNTIME_USER": record["runtime_user"], "REGISTRY_FQDN": record["fqdn"]}
    (BASE / "hosts" / (node + ".env")).write_text("".join(f"{k}={v}\n" for k, v in data.items()))
