#!/usr/bin/env python3
"""Generate identical standalone trust guards for the legacy delivery seam."""
import pathlib
import json
import shlex
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = ROOT / "hermes_converger/step0"
registry = json.loads((BASE / "host-contracts.json").read_text())
users = sorted({v["runtime_user"] for v in registry.values()} - {"root"})
contain = (BASE / "contain.sh").read_text()
contain = re.sub(r"for user in .*; do # generated runtime users", "for user in " + " ".join(shlex.quote(u) for u in users) + "; do # generated runtime users", contain)
start = contain.index("/usr/bin/awk '") + len("/usr/bin/awk '")
end = contain.index("' \"$f\"", start)
contain = contain[:start] + (BASE / "sudoers.awk").read_text() + contain[end:]
(BASE / "contain.sh").write_text(contain)
TRUST = (BASE / "trust.sh").read_text().split("\n", 1)[1] + (BASE / "contain.sh").read_text().split("\n", 1)[1]
# env -i is before any external helper or imported file. Noninteractive /bin/sh
# reads no ENV/BASH_ENV; sudo also strips dynamic loader variables before exec.
PREFIX = '''#!/bin/sh
# Generated by scripts/render-currency-step0.py; takes NO caller arguments.
[ "$#" = 0 ] || { echo 'chief: arguments refused' >&2; exit 2; }
'''
for name, mode in (("hermes-converger", "converge"), ("chief-node-supervisor", "supervisor"), ("chief-update", "update")):
    body = "cd /\numask 027\n" + TRUST + '''
[ "$(/usr/bin/id -u)" = 0 ] || { hold 'root service entry point'; exit 1; }
BASE=/opt/chief/lib/hermes-host-bootstrap/hermes_converger/step0
if [ ! -d "$BASE" ]; then
    # One-time bridge from the legacy updater's fixed copy destinations. On an
    # untrusted /usr/local chain use the reviewed root archive route instead.
    trusted_path /usr/local/bin/''' + name + ''' || refuse unsafe_launcher_path
    trusted_tree /usr/local/lib/hermes-host-bootstrap/hermes_converger || refuse unsafe_payload_tree
    for dir in /opt /opt/chief /opt/chief/lib /opt/chief/lib/hermes-host-bootstrap /opt/chief/bin; do
        if [ ! -e "$dir" ]; then /usr/bin/install -d -o root -m 0755 "$dir"; fi
        trusted_path "$dir" || refuse unsafe_destination
    done
    /bin/cp -R /usr/local/lib/hermes-host-bootstrap/hermes_converger /opt/chief/lib/hermes-host-bootstrap/
fi
# Only fixed /opt jobs execute after closure. The legacy copies are no longer
# passwordless and are never referenced by a daemon.
if [ -e /opt/chief/bin/''' + name + ''' ]; then
    trusted_path /opt/chief/bin/''' + name + ''' || refuse unsafe_launcher_path
fi
trusted_path "$BASE/trust.sh" || refuse unsafe_payload_path
if [ ! -f /var/lib/chief/currency-step0/grants-removed ] || [ ! -f /var/lib/chief/currency-step0/prepared ]; then
    trusted_tree "$BASE/.." || refuse unsafe_payload_tree
    exec /bin/sh "$BASE/close.sh"
fi
trusted_path /var/lib/chief/currency-step0/grants-removed || refuse unsafe_state
'''
    script = {"converge": "pulse", "supervisor": "supervise", "update": "update"}[mode]
    body += f'trusted_path "$BASE/{script}.sh" || refuse unsafe_entry\n'
    if mode == "update":
        body += 'trusted_tree "$BASE/.." || refuse unsafe_payload_tree\n'
    body += f'exec /bin/sh "$BASE/{script}.sh"\n'
    rendered = PREFIX + "exec /usr/bin/env -i PATH=/usr/bin:/bin:/usr/sbin:/sbin HOME=/var/empty LANG=C /bin/sh -c " + shlex.quote(body) + "\n"
    (ROOT / "scripts" / name).write_text(rendered)
    (BASE / "bin").mkdir(exist_ok=True)
    (BASE / "bin" / name).write_text(rendered)

for folder, pattern in (("systemd", "chief-*"), ("launchd", "com.chief.*.plist")):
    for source in (ROOT / folder).glob(pattern):
        if not source.is_file() or source.name in {"chief-node.service", "chief-update-login.service", "com.chief.node.plist"}:
            continue
        (BASE / folder).mkdir(exist_ok=True)
        (BASE / folder / source.name).write_bytes(source.read_bytes())
for source, target in (("systemd/chief-update-login.service", "chief-update-login.service"),
                       ("scripts/chief-update-resume", "chief-update-resume"),
                       ("scripts/chief-update-request", "bin/chief-update-request")):
    (BASE / target).write_bytes((ROOT / source).read_bytes())

# Snapshot of the authoritative host registry, not a separate SSH inventory.
(BASE / "hosts").mkdir(exist_ok=True)
for old in (BASE / "hosts").glob("*.env"):
    if old.stem not in registry:
        old.unlink()
for node, record in registry.items():
    data = {"CHIEF_NODE_ID": node, "CHIEF_CORE_URL": record["CHIEF_CORE_URL"],
            "CHIEF_RUNTIME_USER": record["runtime_user"], "REGISTRY_FQDN": record["fqdn"]}
    (BASE / "hosts" / (node + ".env")).write_text("".join(f"{k}={v}\n" for k, v in data.items()))
